spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercehardware
    username: postgres
    password: itaChi*19951985
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 472B4B6250655368566D597133743677397A24432646294A404D635166546A57
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
