#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ecommercehardware
#    username: postgres
#    password: itaChi*19951985
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#application:
#  security:
#    jwt:
#      secret-key: 244226452948404D635166546A576E5A7234753777217A25432A462D4A614E64
#      expiration: 60000 # 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
#    username: postgres
#    password: itaChi*19951985
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 244226452948404D635166546A576E5A7234753777217A25432A462D4A614E64
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days